name: test

on: [push, pull_request]

jobs:
  macos-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: init
      run: make init
    - name: deploy
      run: make deploy
    - name: clean
      run: make clean
  ubuntu-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: init
      run: make init
    - name: deploy
      run: make deploy
    - name: clean
      run: make clean