name: test

on: [push]

jobs:
  macos-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make
    - name: init
      run: make init
    - name: deploy
      run: make deploy
    - name: clean
      run: make clean
    - name: help
      run: make help
  ubuntu-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make
    - name: init
      run: make init
    - name: deploy
      run: make deploy
    - name: clean
      run: make clean
    - name: help
      run: make help